#%RAML 1.0 DataType
type: object
properties:
  user:
    type: object
    properties:
      name?: any
      short_name?: any
      sortable_name?: any
      time_zone?: any
      locale?: any
      terms_of_use?: any
      skip_registration?: any
  pseudonym:
    type: object
    properties:
      unique_id?: any
      password?: any
      sis_user_id?: any
      integration_id?: any
      send_confirmation?: any
      force_self_registration?: any
      authentication_provider_id?: any
  communication_channel?:
    type: object
    properties:
      type?: any
      address?: any
      confirmation_url?: any
      skip_confirmation?: any
  force_validations?: any
  enable_sis_reactivation?: any
  destination?: any
  initial_enrollment_type?: any
  pairing_code?:
    type: object
    properties:
      code?: any

