#%RAML 1.0 DataType
type: object
properties:
  id: integer
  name?: string
  created_at?: datetime
  sortable_name?: string
  short_name?: string
  sis_user_id?: string | nil
  integration_id?: string | nil
  root_account?: string
  login_id?: string
