#%RAML 1.0 DataType
type: object
properties:
  course?:
    type: object
    properties:
      account_id?: any
      name?: any
      course_code?: any
      start_at?: any
      end_at?: any
      license?: any
      is_public?: any
      is_public_to_auth_users?: any
      public_syllabus?: any
      public_syllabus_to_auth?: any
      public_description?: any
      allow_student_wiki_edits?: any
      allow_wiki_comments?: any
      allow_student_forum_attachments?: any
      open_enrollment?: any
      self_enrollment?: any
      restrict_enrollments_to_course_dates?: any
      term_id?: any
      sis_course_id?: any
      integration_id?: any
      hide_final_grades?: any
      time_zone?: any
      apply_assignment_group_weights?: any
      default_view?: any
      syllabus_body?: any
      grading_standard_id?: any
      grade_passback_setting?: any
      course_format?: any
      post_manually?: any
      blueprint?: any
      template?: any
      course_color?: any
      friendly_name?: any
      conditional_release?: any
  offer?: any
