#%RAML 1.0 DataType
type: object
properties:
  course_section:
    type: object
    required: true
    properties:
      name?: any 
      sis_section_id?: any
      integration_id?: any
      start_at?: any
      end_at?: any
      restrict_enrollments_to_section_dates?: any
  enable_sis_reactivation?: any
