#%RAML 1.0 DataType
type: object
properties:
  course_section:
    type: object
    properties:
      name?: string
      sis_section_id?: string
      integration_id?: string
      start_at?: datetime
      end_at?: datetime | nil
      restrict_enrollments_to_section_dates?: boolean | nil
  override_sis_stickiness?: boolean
